#ifndef _CARTONLSYSTEMOP_H
#define _CARTONLSYSTEMOP_H

enum CARTON_LSYSTEM {
	CT_FORWARD,
	CT_ROTATE_LEFT,
	CT_ROTATE_RIGHT,
	CT_ROTATE_LEFT_AND_PUSH,
	CT_POP_AND_ROTATE_RIGHT
};

#endif // _KUMALSYSTEMOP_H