#ifndef _MODELER_GLOBALS_H
#define _MODELER_GLOBALS_H

#ifndef M_PI
#define M_PI 3.141592653589793238462643383279502
#endif


// This is a list of the controls for the SampleModel
// We'll use these constants to access the values 
// of the controls from the user interface.
enum SampleModelControls
{ 
	XPOS, YPOS, ZPOS, 

	DRAW_LIGHT,
	LIGHT0_X, LIGHT0_Y, LIGHT0_Z, LIGHT0_DIFFUSE,
	LIGHT1_X, LIGHT1_Y, LIGHT1_Z, LIGHT1_DIFFUSE,

	HEAD_ROTATE_X, HEAD_ROTATE_Y, HEAD_ROTATE_Z,
	
	BODY_ROTATE_X, BODY_ROTATE_Y, BODY_ROTATE_Z,
	
	LEFT_UPPER_ARM_ROTATE_X, LEFT_UPPER_ARM_ROTATE_Y, LEFT_UPPER_ARM_ROTATE_Z,
	LEFT_LOWER_ARM_ROTATE_X, LEFT_LOWER_ARM_ROTATE_Y, LEFT_LOWER_ARM_ROTATE_Z,

	RIGHT_UPPER_ARM_ROTATE_X, RIGHT_UPPER_ARM_ROTATE_Y, RIGHT_UPPER_ARM_ROTATE_Z,
	RIGHT_LOWER_ARM_ROTATE_X, RIGHT_LOWER_ARM_ROTATE_Y, RIGHT_LOWER_ARM_ROTATE_Z,
	
	LEFT_UPPER_LEG_ROTATE_X, LEFT_UPPER_LEG_ROTATE_Y, LEFT_UPPER_LEG_ROTATE_Z,
	RIGHT_UPPER_LEG_ROTATE_X, RIGHT_UPPER_LEG_ROTATE_Y, RIGHT_UPPER_LEG_ROTATE_Z,

	LEFT_LOWER_LEG_ROTATE_X, LEFT_LOWER_LEG_ROTATE_Y, LEFT_LOWER_LEG_ROTATE_Z,
	RIGHT_LOWER_LEG_ROTATE_X, RIGHT_LOWER_LEG_ROTATE_Y, RIGHT_LOWER_LEG_ROTATE_Z,

	DETAIL_LEVEL,

	HEAD_WIDTH, HEAD_HEIGHT, HEAD_DEPTH,
	EYE_OFFSET_X, EYE_OFFSET_Y, EYE_RADIUS,
	MOUTH_WIDTH, MOUTH_HEIGHT, MOUTH_OFFSET_Y,
	BODY_WIDTH, BODY_HEIGHT, BODY_DEPTH,

	UPPER_ARM_WIDTH, UPPER_ARM_HEIGHT, UPPER_ARM_DEPTH,
	LOWER_ARM_WIDTH, LOWER_ARM_HEIGHT, LOWER_ARM_DEPTH,

	UPPER_LEG_WIDTH, UPPER_LEG_HEIGHT, UPPER_LEG_DEPTH,
	LOWER_LEG_WIDTH, LOWER_LEG_HEIGHT, LOWER_LEG_DEPTH,

	NUMCONTROLS

};

// Colors
#define COLOR_RED		1.0f, 0.0f, 0.0f
#define COLOR_GREEN		0.0f, 1.0f, 0.0f
#define COLOR_BLUE		0.0f, 0.0f, 1.0f

// We'll be getting the instance of the application a lot; 
// might as well have it as a macro.
#define VAL(x) (ModelerApplication::Instance()->GetControlValue(x))
#define SETVAL(x, v) (ModelerApplication::Instance()->SetControlValue(x, v))

#endif